'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';

type Address = { title?: string; formattedAddress?: string };
type Courier = { id:string; phone:string; vehicleType:string; status:string; lastLatitude:number|null; lastLongitude:number|null; lastSeenAt:string|null };
type Order = { id:string; publicCode:string; status:string; vehicleType:string; pickupSnapshot:Address; dropoffSnapshot:Address; quotedPriceToman:number; finalPriceToman:number|null; distanceMeters:number; customer?:{phone:string}|null; courier?:{id:string;phone:string|null;status:string}|null; courierId:string|null; createdAt:string };
type Event = { id:string; eventType:string; fromStatus:string|null; toStatus:string|null; createdAt:string };
type OrderDetail = Order & { events:Event[]; notes:string|null };

const labels:Record<string,string>={REQUESTED:'در انتظار پیک',ASSIGNED:'تخصیص داده شد',PICKED_UP:'در مسیر مقصد',DELIVERED:'تحویل شد',CANCELLED:'لغو شد',OFFLINE:'آفلاین',AVAILABLE:'آماده',BUSY:'مشغول',SUSPENDED:'تعلیق'};
const filters=['ALL','REQUESTED','ASSIGNED','PICKED_UP','DELIVERED'] as const;
const filterLabels:Record<string,string>={ALL:'همه',REQUESTED:'جدید',ASSIGNED:'تخصیص',PICKED_UP:'در مسیر',DELIVERED:'تحویل‌شده'};
const eventLabels:Record<string,string>={ORDER_REQUESTED:'سفارش ثبت شد',ORDER_ACCEPTED_BY_COURIER:'پیک سفارش را پذیرفت',ORDER_REJECTED_BY_COURIER:'پیک مأموریت را رد کرد',ORDER_ASSIGNED_BY_ADMIN:'مدیر پیک اختصاص داد',ORDER_REASSIGNED_BY_ADMIN:'مدیر پیک را تغییر داد',ORDER_PICKED_UP:'بسته دریافت شد',ORDER_DELIVERED:'سفارش تحویل شد',ORDER_CANCELLED_BY_CUSTOMER:'مشتری سفارش را لغو کرد'};
const toman=(n:number)=>new Intl.NumberFormat('fa-IR').format(n);

export default function AdminHome(){
 const router=useRouter(); const [orders,setOrders]=useState<Order[]>([]); const [couriers,setCouriers]=useState<Courier[]>([]); const [filter,setFilter]=useState<string>('ALL'); const [detail,setDetail]=useState<OrderDetail|null>(null); const [courierId,setCourierId]=useState(''); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
 const api=useCallback(async(path:string,init?:RequestInit)=>{const r=await fetch(`/api/admin/${path}`,{...init,cache:'no-store'}); if(r.status===401||r.status===403){router.replace('/');throw new Error('نشست مدیریت پایان یافته')} const b=await r.json().catch(()=>({})); if(!r.ok)throw new Error(b.message??'درخواست ناموفق بود');return b},[router]);
 const load=useCallback(async()=>{const [o,c]=await Promise.all([api('orders') as Promise<Order[]>,api('couriers') as Promise<Courier[]>]);setOrders(o);setCouriers(c)},[api]);
 useEffect(()=>{load().catch(e=>setError(e instanceof Error?e.message:'خطا')).finally(()=>setLoading(false));const t=setInterval(()=>void load().catch(()=>undefined),15000);return()=>clearInterval(t)},[load]);
 const shown=useMemo(()=>filter==='ALL'?orders:orders.filter(o=>o.status===filter),[orders,filter]);
 const counts={requested:orders.filter(o=>o.status==='REQUESTED').length,active:orders.filter(o=>['ASSIGNED','PICKED_UP'].includes(o.status)).length,available:couriers.filter(c=>c.status==='AVAILABLE').length,delivered:orders.filter(o=>o.status==='DELIVERED').length};
 async function selectOrder(id:string){setError('');try{const d=await api(`orders/${id}`) as OrderDetail;setDetail(d);setCourierId('')}catch(e){setError(e instanceof Error?e.message:'خطا در جزئیات')}}
 async function dispatch(){if(!detail||!courierId)return;setBusy(true);setError('');try{const action=detail.status==='REQUESTED'?'assign':'reassign';await api(`orders/${detail.id}/${action}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({courierId})});await load();await selectOrder(detail.id)}catch(e){setError(e instanceof Error?e.message:'تخصیص ناموفق بود')}finally{setBusy(false)}}
 async function logout(){await fetch('/api/session/logout',{method:'POST'}).catch(()=>undefined);router.replace('/')}
 const eligible=detail?couriers.filter(c=>c.status==='AVAILABLE'&&c.vehicleType===detail.vehicleType):[];
 return <main className="admin-shell">
  <header className="topbar"><div className="identity"><div className="mark">م</div><div><span>ارسال بهشهر</span><strong>مرکز عملیات</strong></div></div><div className="top-actions"><button className="tiny-button" onClick={()=>router.push('/pricing')}>قیمت‌گذاری</button><button className="tiny-button" onClick={()=>void load()}>بروزرسانی</button><button className="tiny-button" onClick={()=>void logout()}>خروج</button></div></header>
  {error?<p className="error">{error}</p>:null}
  <section className="summary"><div className="card metric"><span>سفارش جدید</span><strong>{counts.requested.toLocaleString('fa-IR')}</strong></div><div className="card metric"><span>مأموریت فعال</span><strong>{counts.active.toLocaleString('fa-IR')}</strong></div><div className="card metric"><span>پیک آماده</span><strong>{counts.available.toLocaleString('fa-IR')}</strong></div><div className="card metric"><span>تحویل‌شده در لیست</span><strong>{counts.delivered.toLocaleString('fa-IR')}</strong></div></section>
  <div className="workspace">
   <section className="card panel"><div className="panel-head"><h2>برد سفارش‌ها</h2><div className="filters">{filters.map(f=><button key={f} className={`filter ${filter===f?'active':''}`} onClick={()=>setFilter(f)}>{filterLabels[f]}</button>)}</div></div>{loading?<div className="empty">در حال دریافت…</div>:<div className="table-wrap"><table className="orders-table"><thead><tr><th>کد</th><th>وضعیت</th><th>مشتری</th><th>وسیله</th><th>کرایه</th><th>پیک</th><th>زمان</th></tr></thead><tbody>{shown.map(o=><tr key={o.id} className={detail?.id===o.id?'selected':''} onClick={()=>void selectOrder(o.id)}><td><span className="code">{o.publicCode}</span></td><td><span className={`status status-${o.status.toLowerCase()}`}>{labels[o.status]??o.status}</span></td><td dir="ltr">{o.customer?.phone??'—'}</td><td>{o.vehicleType==='MOTORBIKE'?'موتور':'خودرو'}</td><td>{toman(o.finalPriceToman??o.quotedPriceToman)}</td><td dir="ltr">{o.courier?.phone??'—'}</td><td>{new Date(o.createdAt).toLocaleTimeString('fa-IR',{hour:'2-digit',minute:'2-digit'})}</td></tr>)}</tbody></table>{!shown.length?<div className="empty">سفارشی در این وضعیت نیست.</div>:null}</div>}</section>
   <aside className="side">
    <section className="card panel"><div className="panel-head"><h2>ناوگان</h2><span className="muted">{couriers.length.toLocaleString('fa-IR')} پیک</span></div><div className="courier-list">{couriers.map(c=><div className="courier" key={c.id}><div><strong dir="ltr">{c.phone}</strong><span>{c.vehicleType==='MOTORBIKE'?'موتور':'خودرو'}{c.lastSeenAt?` • GPS ${new Date(c.lastSeenAt).toLocaleTimeString('fa-IR',{hour:'2-digit',minute:'2-digit'})}`:''}</span>{c.lastLatitude!==null&&c.lastLongitude!==null?<a className="muted" href={`geo:${c.lastLatitude},${c.lastLongitude}?q=${c.lastLatitude},${c.lastLongitude}`}>موقعیت</a>:null}</div><span className={`courier-state ${c.status.toLowerCase()}`}>{labels[c.status]??c.status}</span></div>)}</div></section>
    <section className="card panel">{detail?<div className="detail"><div className="detail-head"><div><span className="muted">جزئیات سفارش</span><h3 className="code">{detail.publicCode}</h3></div><span className={`status status-${detail.status.toLowerCase()}`}>{labels[detail.status]??detail.status}</span></div><div className="route"><div><span>مبدا</span><strong>{detail.pickupSnapshot?.title??'مبدا'}</strong><p>{detail.pickupSnapshot?.formattedAddress??'—'}</p></div><div><span>مقصد</span><strong>{detail.dropoffSnapshot?.title??'مقصد'}</strong><p>{detail.dropoffSnapshot?.formattedAddress??'—'}</p></div></div>{['REQUESTED','ASSIGNED'].includes(detail.status)?<div className="dispatch"><label>{detail.status==='REQUESTED'?'تخصیص پیک':'جابه‌جایی به پیک دیگر'}</label><div className="dispatch-row"><select className="select" value={courierId} onChange={e=>setCourierId(e.target.value)}><option value="">انتخاب پیک آماده</option>{eligible.map(c=><option key={c.id} value={c.id}>{c.phone} • {c.vehicleType==='MOTORBIKE'?'موتور':'خودرو'}</option>)}</select><button className="primary" disabled={!courierId||busy} onClick={()=>void dispatch()}>{busy?'…':'ثبت'}</button></div>{!eligible.length?<p className="muted">پیک آماده و هم‌نوع وسیله وجود ندارد.</p>:null}</div>:null}<div className="timeline"><h4>روند سفارش</h4>{detail.events?.map(e=><div className="event" key={e.id}><strong>{eventLabels[e.eventType]??e.eventType}</strong><span>{new Date(e.createdAt).toLocaleString('fa-IR')}</span></div>)}</div></div>:<div className="detail-empty">برای مشاهده جزئیات و تخصیص پیک، یک سفارش را از جدول انتخاب کن.</div>}</section>
   </aside>
  </div>
 </main>
}
